Added version compatibility table
plaid/react-native-plaid-link-sdk pull request #170
Opened 2020-08-18 17:39 UTC by zsweigart

2020-08-19 09:25 UTC, afh requested changes
What are your thoughts on the suggestions for iOS version compatibility as well as a table header title for the last column, @zsweigart?

2020-08-19 09:25 UTC, afh commented on README.md
> +| 1.x.x | [0.1.0-0.3.0) |   |  Deprecated |
Add iOS SDK version compatibility for 1.x.x
```suggestion
| 1.x.x | [0.1.0-0.3.0) | <=1.1.24 |  Deprecated |
```

2020-08-19 09:25 UTC, afh commented on README.md
> +| 2.x.x | [0.3.0-1.0.0) |   |  Deprecated |
Add iOS SDK version compatibility for 2.x.x
```suggestion
| 2.x.x | [0.3.0-1.0.0) | <=1.1.27 |  Deprecated |
```

2020-08-19 09:25 UTC, afh commented on README.md
> +| 3.x.x | [1.0.0-2.0.0) |   |  Deprecated |
Add iOS SDK version compatibility for 3.x.x
```suggestion
| 3.x.x | [1.0.0-2.0.0) | v.s. |  Deprecated |
```

2020-08-19 09:25 UTC, afh commented on README.md
> +| 4.x.x | [2.0.0-2.1.0) |   |  |
Add iOS SDK version compatibility for 4.x.x
```suggestion
| 4.x.x | [2.0.0-2.1.0) | <=1.1.33 | Active |
```

2020-08-19 09:25 UTC, afh commented on README.md
> +| 5.x.x | [2.1.0+) |   |  |
Add iOS SDK version compatibility for 5.x.x
```suggestion
| 5.x.x | [2.1.0+) | >=1.1.34 | Active |
```

2020-08-19 13:42 UTC, zsweigart commented
I just kept it simple by repeating the line

2020-08-25 15:37 UTC, afh approved these changes
Thanks for considering my suggestions, @zsweigart.
Find below some minor suggestions for consistent use of blankspace; I leave addressing these (or not) at your discretion.

2020-08-25 15:37 UTC, afh commented on README.md
> +|---|---|---| --- |
📐 Consistent use of blankspace would be greatly appreciated by OCD people ;)
```suggestion
|---|---|---|---|
```

2020-08-25 15:37 UTC, afh commented on README.md
> +| 5.x.x | [2.1.0+) | >=1.1.34 | Active |
📐 Aligning the table columns would be greatly appreciated by OCD people ;)
```suggestion
| 5.x.x | [2.1.0+)      | >=1.1.34 | Active |
```

2020-08-26 13:34 UTC, afh approved these changes
Great work @zsweigart!

2020-08-26 14:34 UTC, merged