RN: Add sample app
plaid/react-native-plaid-link-sdk pull request #231
Opened 2020-10-27 18:37 UTC by amytang0

2020-10-28 15:01 UTC, zsweigart approved these changes

2020-11-03 19:33 UTC, JeroenMols requested changes

2020-11-03 19:33 UTC, JeroenMols commented on example/android/app/build.gradle
> +        implementation 'com.plaid.link:sdk-core:3.0.1+'
```suggestion
```

This can be removed, SDK version is consumed transitively through Plaid  RN sdk

2020-11-03 19:34 UTC, JeroenMols approved these changes

2020-11-04 21:57 UTC, merged