Add deposit switch product
plaid/react-native-plaid-link-sdk pull request #245
Opened 2020-11-04 17:26 UTC by jeffzwang

2020-11-04 18:13 UTC, zsweigart requested changes
We're updating types soon, so this will have to be updated.

2020-11-04 18:13 UTC, zsweigart commented on android/src/main/java/com/plaid/PlaidModule.kt
> +    if (!token.startsWith(LINK_TOKEN_PREFIX) && !token.startsWith(LINK_TOKEN_PREFIX)) {
```suggestion
    if (!token.startsWith(LINK_TOKEN_PREFIX) && !token.startsWith(DEPOSIT_SWITCH_TOKEN_PREFIX)) {
```

2020-11-04 21:05 UTC, zsweigart approved these changes

2020-11-04 21:55 UTC, amytang0 requested changes
RC for requiring the underlying SDKs

2020-11-20 10:01 UTC, JeroenMols commented
Closing this PR as we are in the midst of a typescript conversion.

- The non typescript SDK 6.0.4 already has `deposit_switch` added
- The typescript SDK 7.x will get `deposit_switch` through https://github.com/plaid/react-native-plaid-link-sdk/pull/269

2020-11-20 10:01 UTC, closed without merging