Fix Product, Log Level and Extra Params
plaid/react-native-plaid-link-sdk pull request #269
Opened 2020-11-19 21:58 UTC by zsweigart

Fix Product, Log Level and Extra Params for Android

2020-11-19 23:31 UTC, amytang0 commented on Types.ts
> +    DEPOSIT_SWITCH="deposit_switch",
nice, ty

2020-11-19 23:32 UTC, amytang0 commented on android/src/main/java/com/plaid/PlaidModule.kt
> +    private const val EXTRAS = "extraParams"
this might need to go in another PR, we probably broke iOS

2020-11-19 23:37 UTC, amytang0 requested changes
Mostly LGTM, revert change for extraParams since it will break iOS

2020-11-20 09:55 UTC, JeroenMols approved these changes

2020-11-20 14:17 UTC, zsweigart commented
@amytang0 I had to rename the type  in js to `extras` as well

2020-11-20 19:16 UTC, amytang0 approved these changes
LGTM

2020-11-20 19:33 UTC, merged